package view.ocorrencia;

import java.awt.*; import javax.swing.*; import javax.swing.table.DefaultTableModel;
import controller.*; import model.*; import util.FormUtils; import view.StyleUtils;

public class OcorrenciaView extends JPanel {
    private JTable tabela; private DefaultTableModel tableModel; private JButton btnNovo,btnEditar,btnExcluir,btnAtualizar; private OcorrenciaController controller=new OcorrenciaController(); private EquipamentoController equipamentoController=new EquipamentoController();
    public OcorrenciaView(){inicializar();configurarEventos();carregarTabela();}
    private void inicializar(){setLayout(new BorderLayout()); StyleUtils.styleView(this); JPanel p=StyleUtils.toolbar(); btnNovo=new JButton("Novo");btnEditar=new JButton("Editar");btnExcluir=new JButton("Excluir");btnAtualizar=new JButton("Atualizar"); StyleUtils.styleToolbarButton(btnNovo); StyleUtils.styleToolbarButton(btnEditar); StyleUtils.styleDangerButton(btnExcluir); StyleUtils.styleToolbarButton(btnAtualizar); p.add(btnNovo);p.add(btnEditar);p.add(btnExcluir);p.add(btnAtualizar); add(p,BorderLayout.NORTH); tableModel=new DefaultTableModel(new String[]{"ID","Equipamento","Descrição","Data","Status"},0){public boolean isCellEditable(int r,int c){return false;}}; tabela=new JTable(tableModel); add(StyleUtils.tableScroll(tabela),BorderLayout.CENTER);}
    private void configurarEventos(){btnNovo.addActionListener(e->abrirDialog(null));btnEditar.addActionListener(e->editar());btnExcluir.addActionListener(e->excluir());btnAtualizar.addActionListener(e->carregarTabela());}
    private void carregarTabela(){tableModel.setRowCount(0); for(Ocorrencia o:controller.listar()) tableModel.addRow(new Object[]{o.getId(),o.getEquipamento(),o.getDescricao(),o.getData(),o.getStatus()});}
    private void popular(OcorrenciaDialog d){d.getCbEquipamento().removeAllItems(); for(Equipamento e:equipamentoController.listar()) d.getCbEquipamento().addItem(e.toString());}
    private void editar(){int row=tabela.getSelectedRow(); if(row<0){FormUtils.info("Selecione um registro para editar.");return;} int m=tabela.convertRowIndexToModel(row); Ocorrencia obj=new Ocorrencia(); obj.setId((int)tableModel.getValueAt(m,0)); obj.setDescricao(String.valueOf(tableModel.getValueAt(m,2))); obj.setData(FormUtils.parseDate(String.valueOf(tableModel.getValueAt(m,3)),"Data")); obj.setStatus(String.valueOf(tableModel.getValueAt(m,4))); abrirDialog(obj);}
    private void excluir(){int id=FormUtils.selectedTableId(tabela); if(id<0){FormUtils.info("Selecione um registro para excluir.");return;} if(FormUtils.confirmar("Deseja excluir esta ocorrência?")){controller.deletar(id);carregarTabela();}}
    private void abrirDialog(Ocorrencia existente){OcorrenciaDialog d=new OcorrenciaDialog(); popular(d); if(existente!=null){d.getTxtDescricao().setText(existente.getDescricao());d.getDataChooser().setDate(StyleUtils.toUtilDate(existente.getData()));d.getCbStatus().setSelectedItem(existente.getStatus());} d.getBtnCancelar().addActionListener(e->d.dispose()); d.getBtnSalvar().addActionListener(e->{try{Ocorrencia o=existente==null?new Ocorrencia():existente; Equipamento eq=new Equipamento(); eq.setId(FormUtils.selectedId(d.getCbEquipamento(),"Equipamento")); o.setEquipamento(eq); o.setDescricao(d.getTxtDescricao().getText().trim()); o.setData(StyleUtils.getSqlDate(d.getDataChooser(), "Data")); o.setStatus(String.valueOf(d.getCbStatus().getSelectedItem())); if(existente==null) controller.salvar(o); else controller.atualizar(o); d.dispose(); carregarTabela();}catch(Exception ex){FormUtils.erro(ex);}}); d.setVisible(true);}
    public JTable getTabela(){return tabela;} public DefaultTableModel getTableModel(){return tableModel;} public JButton getBtnNovo(){return btnNovo;} public JButton getBtnEditar(){return btnEditar;} public JButton getBtnExcluir(){return btnExcluir;} public JButton getBtnAtualizar(){return btnAtualizar;}
}
