package view.combustivel;

import java.awt.*; import javax.swing.*; import javax.swing.table.DefaultTableModel;
import controller.CombustivelController; import model.Combustivel; import util.FormUtils; import view.StyleUtils;

public class CombustivelView extends JPanel {
    private JTable tabela; private DefaultTableModel tableModel; private JButton btnNovo,btnEditar,btnExcluir,btnAtualizar; private CombustivelController controller=new CombustivelController();
    public CombustivelView(){ inicializar(); configurarEventos(); carregarTabela(); }
    private void inicializar(){ setLayout(new BorderLayout()); StyleUtils.styleView(this); JPanel p=StyleUtils.toolbar(); btnNovo=new JButton("Novo");btnEditar=new JButton("Editar");btnExcluir=new JButton("Excluir");btnAtualizar=new JButton("Atualizar"); StyleUtils.styleToolbarButton(btnNovo); StyleUtils.styleToolbarButton(btnEditar); StyleUtils.styleDangerButton(btnExcluir); StyleUtils.styleToolbarButton(btnAtualizar); p.add(btnNovo);p.add(btnEditar);p.add(btnExcluir);p.add(btnAtualizar); add(p,BorderLayout.NORTH); tableModel=new DefaultTableModel(new String[]{"ID","Tipo","Litros","Estoque Mínimo"},0){public boolean isCellEditable(int r,int c){return false;}}; tabela=new JTable(tableModel); add(StyleUtils.tableScroll(tabela),BorderLayout.CENTER); }
    private void configurarEventos(){ btnNovo.addActionListener(e->abrirDialog(null)); btnEditar.addActionListener(e->editar()); btnExcluir.addActionListener(e->excluir()); btnAtualizar.addActionListener(e->carregarTabela()); }
    private void carregarTabela(){ tableModel.setRowCount(0); for(Combustivel c:controller.listar()) tableModel.addRow(new Object[]{c.getId(),c.getTipo(),c.getLitros(),c.getEstoqueMinimo()}); }
    private void editar(){ int row=tabela.getSelectedRow(); if(row<0){FormUtils.info("Selecione um registro para editar.");return;} int m=tabela.convertRowIndexToModel(row); Combustivel c=new Combustivel(); c.setId((int)tableModel.getValueAt(m,0)); c.setTipo(String.valueOf(tableModel.getValueAt(m,1))); c.setLitros(Double.parseDouble(tableModel.getValueAt(m,2).toString())); c.setEstoqueMinimo(Double.parseDouble(tableModel.getValueAt(m,3).toString())); abrirDialog(c); }
    private void excluir(){ int id=FormUtils.selectedTableId(tabela); if(id<0){FormUtils.info("Selecione um registro para excluir.");return;} if(FormUtils.confirmar("Deseja excluir este combustível?")){controller.deletar(id);carregarTabela();}}
    private void abrirDialog(Combustivel existente){ CombustivelDialog d=new CombustivelDialog(); if(existente!=null){d.getComboTipo().setSelectedItem(existente.getTipo());d.getTxtLitros().setText(String.valueOf(existente.getLitros()));d.getTxtEstoqueMinimo().setText(String.valueOf(existente.getEstoqueMinimo()));} d.getBtnCancelar().addActionListener(e->d.dispose()); d.getBtnSalvar().addActionListener(e->{try{Combustivel c=existente==null?new Combustivel():existente; c.setTipo(String.valueOf(d.getComboTipo().getSelectedItem())); c.setLitros(FormUtils.parseDouble(d.getTxtLitros().getText(),"Litros")); c.setEstoqueMinimo(FormUtils.parseDouble(d.getTxtEstoqueMinimo().getText(),"Estoque mínimo")); if(c.getTipo().isBlank()) throw new IllegalArgumentException("Tipo é obrigatório."); if(existente==null) controller.salvar(c); else controller.atualizar(c); d.dispose(); carregarTabela();}catch(Exception ex){FormUtils.erro(ex);}}); d.setVisible(true); }
    public JTable getTabela(){return tabela;} public DefaultTableModel getTableModel(){return tableModel;} public JButton getBtnNovo(){return btnNovo;} public JButton getBtnEditar(){return btnEditar;} public JButton getBtnExcluir(){return btnExcluir;} public JButton getBtnAtualizar(){return btnAtualizar;}
}
