package view.abastecimento;

import java.awt.*; import javax.swing.*; import javax.swing.table.DefaultTableModel;
import controller.*; import model.*; import util.FormUtils; import util.TableExportUtils; import util.ExcelImportUtils;
import security.PermissionManager; import view.StyleUtils;

public class AbastecimentoView extends JPanel {
    private JTable tabela; private DefaultTableModel tableModel; private JButton btnNovo,btnEditar,btnExcluir,btnAtualizar,btnExportar,btnImportar;
    private AbastecimentoController controller=new AbastecimentoController(); private EquipamentoController equipamentoController=new EquipamentoController(); private CombustivelController combustivelController=new CombustivelController();
    public AbastecimentoView(){inicializar();configurarEventos();carregarTabela();}
    private void inicializar(){setLayout(new BorderLayout()); StyleUtils.styleView(this); JPanel p=StyleUtils.toolbar(); btnNovo=new JButton("Novo");btnEditar=new JButton("Editar");btnExcluir=new JButton("Excluir");btnAtualizar=new JButton("Atualizar");btnExportar=new JButton("Exportar CSV");btnImportar=new JButton("Importar Excel/CSV"); StyleUtils.styleToolbarButton(btnNovo); StyleUtils.styleToolbarButton(btnEditar); StyleUtils.styleDangerButton(btnExcluir); StyleUtils.styleSecondaryButton(btnAtualizar); StyleUtils.styleSecondaryButton(btnExportar);StyleUtils.styleSecondaryButton(btnImportar); p.add(btnNovo);p.add(btnEditar);p.add(btnExcluir);p.add(btnAtualizar);p.add(btnExportar);p.add(btnImportar); PermissionManager.aplicarCrud(this, "abastecimento", btnNovo, btnEditar, btnExcluir); PermissionManager.aplicar(btnImportar, PermissionManager.podeModuloAcao("abastecimento", "importar"), "Seu perfil não permite importar neste módulo."); add(StyleUtils.criarTopoModulo("Abastecimentos", "Controle os lançamentos de consumo de combustível", p),BorderLayout.NORTH); tableModel=new DefaultTableModel(new String[]{"ID","Equipamento","Combustível","Litros","Data"},0){public boolean isCellEditable(int r,int c){return false;}}; tabela=new JTable(tableModel); StyleUtils.adicionarPesquisa(p,tabela); add(StyleUtils.tableScroll(tabela),BorderLayout.CENTER);}
    private void configurarEventos(){btnNovo.addActionListener(e->abrirDialog(null));btnEditar.addActionListener(e->editar());btnExcluir.addActionListener(e->excluir());btnAtualizar.addActionListener(e->carregarTabela());btnExportar.addActionListener(e->TableExportUtils.exportarCSV(this,tabela,"abastecimento"));btnImportar.addActionListener(e->ExcelImportUtils.importarAbastecimentos(this,this::carregarTabela));}
    private void carregarTabela(){tableModel.setRowCount(0); for(Abastecimento a:controller.listar()) tableModel.addRow(new Object[]{a.getId(),a.getEquipamento(),a.getCombustivel(),a.getLitros(),a.getData()});}
    private void popular(AbastecimentoDialog d){d.getComboEquipamento().removeAllItems(); for(Equipamento e:equipamentoController.listar()) d.getComboEquipamento().addItem(e.toString()); d.getComboCombustivel().removeAllItems(); for(Combustivel c:combustivelController.listar()) d.getComboCombustivel().addItem(c.toString());}
    private void editar(){int row=tabela.getSelectedRow(); if(row<0){FormUtils.info("Selecione um registro para editar.");return;} int m=tabela.convertRowIndexToModel(row); Abastecimento a=new Abastecimento(); a.setId((int)tableModel.getValueAt(m,0)); a.setLitros(Double.parseDouble(tableModel.getValueAt(m,3).toString())); a.setData(FormUtils.parseDate(String.valueOf(tableModel.getValueAt(m,4)),"Data")); abrirDialog(a);}
    private void excluir(){int id=FormUtils.selectedTableId(tabela); if(id<0){FormUtils.info("Selecione um registro para excluir.");return;} if(FormUtils.confirmar("Deseja excluir este abastecimento?")){controller.deletar(id);carregarTabela();}}
    private void abrirDialog(Abastecimento existente){AbastecimentoDialog d=new AbastecimentoDialog(); popular(d); if(existente!=null){d.getTxtLitros().setText(String.valueOf(existente.getLitros())); d.getDataChooser().setDate(StyleUtils.toUtilDate(existente.getData()));} d.getBtnCancelar().addActionListener(e->d.dispose()); d.getBtnSalvar().addActionListener(e->{try{Abastecimento a=existente==null?new Abastecimento():existente; Equipamento eq=new Equipamento(); eq.setId(FormUtils.selectedId(d.getComboEquipamento(),"Equipamento")); Combustivel cb=new Combustivel(); cb.setId(FormUtils.selectedId(d.getComboCombustivel(),"Combustível")); a.setEquipamento(eq);a.setCombustivel(cb);a.setLitros(FormUtils.parseDouble(d.getTxtLitros().getText(),"Litros"));a.setData(StyleUtils.getSqlDate(d.getDataChooser(), "Data")); if(existente==null) controller.salvar(a); else controller.atualizar(a); d.dispose(); carregarTabela();}catch(Exception ex){FormUtils.erro(ex);}}); d.setVisible(true);}
    public JTable getTabela(){return tabela;} public DefaultTableModel getTableModel(){return tableModel;} public JButton getBtnNovo(){return btnNovo;} public JButton getBtnEditar(){return btnEditar;} public JButton getBtnExcluir(){return btnExcluir;} public JButton getBtnAtualizar(){return btnAtualizar;} public JButton getBtnExportar(){return btnExportar;} public JButton getBtnImportar(){return btnImportar;}
}
