package view.licitacao;

import java.awt.*; import javax.swing.*; import javax.swing.table.DefaultTableModel;
import controller.*; import model.*; import util.FormUtils; import view.StyleUtils;

public class LicitacaoView extends JPanel {
    private JTable tabela; private DefaultTableModel tableModel; private JButton btnNovo,btnEditar,btnExcluir,btnAtualizar; private LicitacaoController controller=new LicitacaoController(); private EmpenhoController empenhoController=new EmpenhoController();
    public LicitacaoView(){inicializar();configurarEventos();carregarTabela();}
    private void inicializar(){setLayout(new BorderLayout()); StyleUtils.styleView(this); JPanel p=StyleUtils.toolbar(); btnNovo=new JButton("Novo");btnEditar=new JButton("Editar");btnExcluir=new JButton("Excluir");btnAtualizar=new JButton("Atualizar"); StyleUtils.styleToolbarButton(btnNovo); StyleUtils.styleToolbarButton(btnEditar); StyleUtils.styleDangerButton(btnExcluir); StyleUtils.styleToolbarButton(btnAtualizar); p.add(btnNovo);p.add(btnEditar);p.add(btnExcluir);p.add(btnAtualizar); add(p,BorderLayout.NORTH); tableModel=new DefaultTableModel(new String[]{"ID","Número","Objeto","Modalidade","Empresa","Valor","Data","Empenho"},0){public boolean isCellEditable(int r,int c){return false;}}; tabela=new JTable(tableModel); add(StyleUtils.tableScroll(tabela),BorderLayout.CENTER);}
    private void configurarEventos(){btnNovo.addActionListener(e->abrirDialog(null));btnEditar.addActionListener(e->editar());btnExcluir.addActionListener(e->excluir());btnAtualizar.addActionListener(e->carregarTabela());}
    private void carregarTabela(){tableModel.setRowCount(0); for(Licitacao l:controller.listar()) tableModel.addRow(new Object[]{l.getId(),l.getNumero(),l.getObjeto(),l.getModalidade(),l.getEmpresa(),l.getValor(),l.getData(),l.getEmpenho()==null?"":l.getEmpenho()});}
    private void popular(LicitacaoDialog d){d.getCbEmpenho().removeAllItems(); d.getCbEmpenho().addItem("0 - Sem empenho"); for(Empenho e:empenhoController.listar()) d.getCbEmpenho().addItem(e.toString());}
    private void editar(){int row=tabela.getSelectedRow(); if(row<0){FormUtils.info("Selecione um registro para editar.");return;} int m=tabela.convertRowIndexToModel(row); Licitacao l=new Licitacao(); l.setId((int)tableModel.getValueAt(m,0)); l.setNumero(String.valueOf(tableModel.getValueAt(m,1))); l.setObjeto(String.valueOf(tableModel.getValueAt(m,2))); l.setModalidade(String.valueOf(tableModel.getValueAt(m,3))); l.setEmpresa(String.valueOf(tableModel.getValueAt(m,4))); l.setValor(Double.parseDouble(tableModel.getValueAt(m,5).toString())); l.setData(FormUtils.parseDate(String.valueOf(tableModel.getValueAt(m,6)),"Data")); abrirDialog(l);}
    private void excluir(){int id=FormUtils.selectedTableId(tabela); if(id<0){FormUtils.info("Selecione um registro para excluir.");return;} if(FormUtils.confirmar("Deseja excluir esta licitação?")){controller.deletar(id);carregarTabela();}}
    private void abrirDialog(Licitacao existente){LicitacaoDialog d=new LicitacaoDialog(); popular(d); if(existente!=null){d.getTxtNumero().setText(existente.getNumero());d.getTxtObjeto().setText(existente.getObjeto());d.getTxtModalidade().setText(existente.getModalidade());d.getTxtEmpresa().setText(existente.getEmpresa());d.getTxtValor().setText(String.valueOf(existente.getValor()));d.getDataChooser().setDate(StyleUtils.toUtilDate(existente.getData()));} d.getBtnCancelar().addActionListener(e->d.dispose()); d.getBtnSalvar().addActionListener(e->{try{Licitacao l=existente==null?new Licitacao():existente; l.setNumero(d.getTxtNumero().getText().trim()); l.setObjeto(d.getTxtObjeto().getText().trim()); l.setModalidade(d.getTxtModalidade().getText().trim()); l.setEmpresa(d.getTxtEmpresa().getText().trim()); l.setValor(FormUtils.parseDouble(d.getTxtValor().getText(),"Valor")); l.setData(StyleUtils.getSqlDate(d.getDataChooser(), "Data")); int empId=FormUtils.selectedId(d.getCbEmpenho(),"Empenho"); if(empId>0){Empenho emp=new Empenho(); emp.setId(empId); l.setEmpenho(emp);} else l.setEmpenho(null); if(l.getNumero().isBlank()||l.getObjeto().isBlank()) throw new IllegalArgumentException("Número e objeto são obrigatórios."); if(existente==null) controller.salvar(l); else controller.atualizar(l); d.dispose(); carregarTabela();}catch(Exception ex){FormUtils.erro(ex);}}); d.setVisible(true);}
    public JTable getTabela(){return tabela;} public DefaultTableModel getTableModel(){return tableModel;} public JButton getBtnNovo(){return btnNovo;} public JButton getBtnEditar(){return btnEditar;} public JButton getBtnExcluir(){return btnExcluir;} public JButton getBtnAtualizar(){return btnAtualizar;}
}
