package view.manutencao;

import java.awt.*; import javax.swing.*; import javax.swing.table.DefaultTableModel;
import controller.*; import model.*; import util.FormUtils; import util.TableExportUtils; import util.ExcelImportUtils;
import security.PermissionManager; import view.StyleUtils;

public class ManutencaoView extends JPanel {
    private JTable tabela; private DefaultTableModel tableModel; private JButton btnNovo,btnEditar,btnExcluir,btnAtualizar,btnExportar,btnImportar; private ManutencaoController controller=new ManutencaoController(); private EquipamentoController equipamentoController=new EquipamentoController();
    public ManutencaoView(){inicializar();configurarEventos();carregarTabela();}
    private void inicializar(){setLayout(new BorderLayout()); StyleUtils.styleView(this); JPanel p=StyleUtils.toolbar(); btnNovo=new JButton("Novo");btnEditar=new JButton("Editar");btnExcluir=new JButton("Excluir");btnAtualizar=new JButton("Atualizar");btnExportar=new JButton("Exportar CSV");btnImportar=new JButton("Importar Excel/CSV"); StyleUtils.styleToolbarButton(btnNovo); StyleUtils.styleToolbarButton(btnEditar); StyleUtils.styleDangerButton(btnExcluir); StyleUtils.styleSecondaryButton(btnAtualizar); StyleUtils.styleSecondaryButton(btnExportar);StyleUtils.styleSecondaryButton(btnImportar); p.add(btnNovo);p.add(btnEditar);p.add(btnExcluir);p.add(btnAtualizar);p.add(btnExportar);p.add(btnImportar); PermissionManager.aplicarCrud(this, "manutencao", btnNovo, btnEditar, btnExcluir); PermissionManager.aplicar(btnImportar, PermissionManager.podeModuloAcao("manutencao", "importar"), "Seu perfil não permite importar neste módulo."); add(StyleUtils.criarTopoModulo("Manutenções", "Registre revisões e serviços realizados na frota", p),BorderLayout.NORTH); tableModel=new DefaultTableModel(new String[]{"ID","Equipamento","Descrição","Revisão Atual","Próxima Revisão","Data"},0){public boolean isCellEditable(int r,int c){return false;}}; tabela=new JTable(tableModel); StyleUtils.adicionarPesquisa(p,tabela); add(StyleUtils.tableScroll(tabela),BorderLayout.CENTER);}
    private void configurarEventos(){btnNovo.addActionListener(e->abrirDialog(null));btnEditar.addActionListener(e->editar());btnExcluir.addActionListener(e->excluir());btnAtualizar.addActionListener(e->carregarTabela());btnExportar.addActionListener(e->TableExportUtils.exportarCSV(this,tabela,"manutencao"));btnImportar.addActionListener(e->ExcelImportUtils.importarManutencoes(this,this::carregarTabela));}
    private void carregarTabela(){tableModel.setRowCount(0); for(Manutencao m:controller.listar()) tableModel.addRow(new Object[]{m.getId(),m.getEquipamento(),m.getDescricao(),m.getRevisaoAtual(),m.getProximaRevisao(),m.getData()});}
    private void popular(ManutencaoDialog d){d.getCbEquipamento().removeAllItems(); for(Equipamento e:equipamentoController.listar()) d.getCbEquipamento().addItem(e.toString());}
    private void editar(){int row=tabela.getSelectedRow(); if(row<0){FormUtils.info("Selecione um registro para editar.");return;} int m=tabela.convertRowIndexToModel(row); Manutencao obj=new Manutencao(); obj.setId((int)tableModel.getValueAt(m,0)); obj.setDescricao(String.valueOf(tableModel.getValueAt(m,2))); obj.setRevisaoAtual(Double.parseDouble(tableModel.getValueAt(m,3).toString())); obj.setProximaRevisao(Double.parseDouble(tableModel.getValueAt(m,4).toString())); obj.setData(FormUtils.parseDate(String.valueOf(tableModel.getValueAt(m,5)),"Data")); abrirDialog(obj);}
    private void excluir(){int id=FormUtils.selectedTableId(tabela); if(id<0){FormUtils.info("Selecione um registro para excluir.");return;} if(FormUtils.confirmar("Deseja excluir esta manutenção?")){controller.deletar(id);carregarTabela();}}
    private void abrirDialog(Manutencao existente){ManutencaoDialog d=new ManutencaoDialog(); popular(d); if(existente!=null){d.getTxtDescricao().setText(existente.getDescricao());d.getTxtRevisaoAtual().setText(String.valueOf(existente.getRevisaoAtual()));d.getTxtProximaRevisao().setText(String.valueOf(existente.getProximaRevisao()));d.getDataChooser().setDate(StyleUtils.toUtilDate(existente.getData()));} d.getBtnCancelar().addActionListener(e->d.dispose()); d.getBtnSalvar().addActionListener(e->{try{Manutencao m=existente==null?new Manutencao():existente; Equipamento eq=new Equipamento(); eq.setId(FormUtils.selectedId(d.getCbEquipamento(),"Equipamento")); m.setEquipamento(eq); m.setDescricao(d.getTxtDescricao().getText().trim()); m.setRevisaoAtual(FormUtils.parseDouble(d.getTxtRevisaoAtual().getText(),"Revisão atual")); m.setProximaRevisao(FormUtils.parseDouble(d.getTxtProximaRevisao().getText(),"Próxima revisão")); m.setData(StyleUtils.getSqlDate(d.getDataChooser(), "Data")); if(existente==null) controller.salvar(m); else controller.atualizar(m); d.dispose(); carregarTabela();}catch(Exception ex){FormUtils.erro(ex);}}); d.setVisible(true);}
    public JTable getTabela(){return tabela;} public DefaultTableModel getTableModel(){return tableModel;} public JButton getBtnNovo(){return btnNovo;} public JButton getBtnEditar(){return btnEditar;} public JButton getBtnExcluir(){return btnExcluir;} public JButton getBtnAtualizar(){return btnAtualizar;} public JButton getBtnExportar(){return btnExportar;} public JButton getBtnImportar(){return btnImportar;}
}
