package view.empenho;

import java.awt.*; import javax.swing.*; import javax.swing.table.DefaultTableModel;
import controller.EmpenhoController; import model.Empenho; import util.FormUtils; import view.StyleUtils;

public class EmpenhoView extends JPanel {
    private JTable tabela; private DefaultTableModel tableModel; private JButton btnNovo,btnEditar,btnExcluir,btnAtualizar; private EmpenhoController controller=new EmpenhoController();
    public EmpenhoView(){ inicializar(); configurarEventos(); carregarTabela(); }
    private void inicializar(){ setLayout(new BorderLayout()); StyleUtils.styleView(this); JPanel p=StyleUtils.toolbar(); btnNovo=new JButton("Novo");btnEditar=new JButton("Editar");btnExcluir=new JButton("Excluir");btnAtualizar=new JButton("Atualizar"); StyleUtils.styleToolbarButton(btnNovo); StyleUtils.styleToolbarButton(btnEditar); StyleUtils.styleDangerButton(btnExcluir); StyleUtils.styleToolbarButton(btnAtualizar); p.add(btnNovo);p.add(btnEditar);p.add(btnExcluir);p.add(btnAtualizar); add(p,BorderLayout.NORTH); tableModel=new DefaultTableModel(new String[]{"ID","Número","Descrição","Categoria","Valor","Saldo","Fornecedor","Data"},0){public boolean isCellEditable(int r,int c){return false;}}; tabela=new JTable(tableModel); add(StyleUtils.tableScroll(tabela),BorderLayout.CENTER); }
    private void configurarEventos(){btnNovo.addActionListener(e->abrirDialog(null));btnEditar.addActionListener(e->editar());btnExcluir.addActionListener(e->excluir());btnAtualizar.addActionListener(e->carregarTabela());}
    private void carregarTabela(){tableModel.setRowCount(0); for(Empenho e:controller.listar()) tableModel.addRow(new Object[]{e.getId(),e.getNumero(),e.getDescricao(),e.getCategoria(),e.getValor(),e.getSaldo(),e.getFornecedor(),e.getData()});}
    private void editar(){int row=tabela.getSelectedRow(); if(row<0){FormUtils.info("Selecione um registro para editar.");return;} int m=tabela.convertRowIndexToModel(row); Empenho e=new Empenho(); e.setId((int)tableModel.getValueAt(m,0)); e.setNumero(String.valueOf(tableModel.getValueAt(m,1))); e.setDescricao(String.valueOf(tableModel.getValueAt(m,2))); e.setCategoria(String.valueOf(tableModel.getValueAt(m,3))); e.setValor(Double.parseDouble(tableModel.getValueAt(m,4).toString())); e.setSaldo(Double.parseDouble(tableModel.getValueAt(m,5).toString())); e.setFornecedor(String.valueOf(tableModel.getValueAt(m,6))); e.setData(FormUtils.parseDate(String.valueOf(tableModel.getValueAt(m,7)),"Data")); abrirDialog(e);}
    private void excluir(){int id=FormUtils.selectedTableId(tabela); if(id<0){FormUtils.info("Selecione um registro para excluir.");return;} if(FormUtils.confirmar("Deseja excluir este empenho?")){controller.deletar(id);carregarTabela();}}
    private void abrirDialog(Empenho existente){EmpenhoDialog d=new EmpenhoDialog(); if(existente!=null){d.getTxtNumero().setText(existente.getNumero());d.getTxtDescricao().setText(existente.getDescricao());d.getTxtCategoria().setText(existente.getCategoria());d.getTxtValor().setText(String.valueOf(existente.getValor()));d.getTxtSaldo().setText(String.valueOf(existente.getSaldo()));d.getTxtFornecedor().setText(existente.getFornecedor());d.getDataChooser().setDate(StyleUtils.toUtilDate(existente.getData()));} d.getBtnCancelar().addActionListener(e->d.dispose()); d.getBtnSalvar().addActionListener(e->{try{Empenho obj=existente==null?new Empenho():existente; obj.setNumero(d.getTxtNumero().getText().trim()); obj.setDescricao(d.getTxtDescricao().getText().trim()); obj.setCategoria(d.getTxtCategoria().getText().trim()); obj.setValor(FormUtils.parseDouble(d.getTxtValor().getText(),"Valor")); obj.setSaldo(FormUtils.parseDouble(d.getTxtSaldo().getText(),"Saldo")); obj.setFornecedor(d.getTxtFornecedor().getText().trim()); obj.setData(StyleUtils.getSqlDate(d.getDataChooser(), "Data")); if(obj.getNumero().isBlank()) throw new IllegalArgumentException("Número é obrigatório."); if(existente==null) controller.salvar(obj); else controller.atualizar(obj); d.dispose(); carregarTabela();}catch(Exception ex){FormUtils.erro(ex);}}); d.setVisible(true);}
    public JTable getTabela(){return tabela;} public DefaultTableModel getTableModel(){return tableModel;} public JButton getBtnNovo(){return btnNovo;} public JButton getBtnEditar(){return btnEditar;} public JButton getBtnExcluir(){return btnExcluir;} public JButton getBtnAtualizar(){return btnAtualizar;}
}
